package org.example.project.model

import kotlinproject.composeapp.generated.resources.*
import org.jetbrains.compose.resources.DrawableResource

data class CardEntity(
    val id: Int,
    val name: String,
    val image: DrawableResource,
)

object CardProvider{
    fun ObtainDeckPart3(): MutableList<CardEntity> {
        return mutableListOf(
            CardEntity(1, "Jotaro Kujo", Res.drawable.jotaro_kujo),
            CardEntity(2, "Joseph Joestar", Res.drawable.joseph_joestar),
            CardEntity(3, "Muhammad Abdol", Res.drawable.muhammad_avdol),
            CardEntity(4, "Noriaki Kakyoin", Res.drawable.noriaki_kakyoin),
            CardEntity(5, "Jean Pierre Polnareff", Res.drawable.jean_pierre_polnareff),
            CardEntity(6, "Iggy", Res.drawable.iggy),
            CardEntity(7, "DIO", Res.drawable.dio),
            CardEntity(8, "Hol Horse", Res.drawable.hol_horse),
            CardEntity(9, "Mariah", Res.drawable.mariah),
            CardEntity(10, "Daniel J.D'arby", Res.drawable.daniel_j_darby),
            CardEntity(11, "Vanilla Ice", Res.drawable.vanilla_ice),
            CardEntity(12, "Forever", Res.drawable.forever),
            CardEntity(13, "Devo the Cursed", Res.drawable.devo),
            CardEntity(14, "Rubber Soul", Res.drawable.rubber_soul),
            CardEntity(15, "J. Geil", Res.drawable.j_geil),
            CardEntity(16, "Enya", Res.drawable.enya),
            CardEntity(17, "Mannish Boy", Res.drawable.mannish_boy),
            CardEntity(18, "N'Doul", Res.drawable.ndoul),
            CardEntity(19, "Alessi", Res.drawable.alessi),
            CardEntity(20, "Pet Shop", Res.drawable.pet_shop),

            CardEntity(1, "Star Platinum", Res.drawable.star_platinum),
            CardEntity(2, "Hermit Purple", Res.drawable.hermit_purple),
            CardEntity(3, "Magician's Red", Res.drawable.magicians_red),
            CardEntity(4, "Hierofant Green", Res.drawable.hierophant_green),
            CardEntity(5, "Silver Chariot", Res.drawable.silver_chariot),
            CardEntity(6, "The Fool", Res.drawable.the_fool),
            CardEntity(7, "The World", Res.drawable.the_world),
            CardEntity(8, "Emperor", Res.drawable.emperor),
            CardEntity(9, "Bastet", Res.drawable.bastet),
            CardEntity(10, "Osiris", Res.drawable.osiris),
            CardEntity(11, "Cream", Res.drawable.cream),
            CardEntity(12, "Strength", Res.drawable.strength),
            CardEntity(13, "Ebony Devil", Res.drawable.ebony_devil),
            CardEntity(15, "Hanged Man", Res.drawable.yellow_temperance),
            CardEntity(16, "Justice", Res.drawable.hanged_man),
            CardEntity(17, "Death Thirteen", Res.drawable.death_13),
            CardEntity(18, "Geb", Res.drawable.geb),
            CardEntity(19, "Sethan", Res.drawable.sethan),
            CardEntity(20, "Horus", Res.drawable.horus),
            )
    }

    fun ObtainDeckPart4(): MutableList<CardEntity> {
        return mutableListOf(
            CardEntity(1, "Josuke Higashikata", Res.drawable.josuke_higashikata),
            CardEntity(2, "Koichi Hirose", Res.drawable.koichi_hirose),
            CardEntity(3, "Okuyasu Nijimura", Res.drawable.okuyasu_nijimura),
            CardEntity(4, "Rohan Kishibe", Res.drawable.rohan_kishibe),
            CardEntity(5, "Yoshikage Kira", Res.drawable.kira_yoshikage),
            CardEntity(6, "Angelo Katagiri", Res.drawable.angelo),
            CardEntity(7, "Keicho Nijimura", Res.drawable.keicho_nijimura),
            CardEntity(8, "Tamami Kobayashi", Res.drawable.tamami_kobayashi),
            CardEntity(9, "Toshikazu Hazamada", Res.drawable.hazamada),
            CardEntity(10, "Yukako Yamagishi", Res.drawable.yukako),
            CardEntity(11, "Akira Otoishi", Res.drawable.akira_otoishi),
            CardEntity(12, "Rat", Res.drawable.bugeaten),
            CardEntity(13, "Shigechi Yangu", Res.drawable.shigechi),
            CardEntity(14, "Yoshihiro Kira", Res.drawable.yoshihiro_kira),
            CardEntity(15, "Ken Oyanagi", Res.drawable.ken_oyanagi),
            CardEntity(16, "Yuya Fungami", Res.drawable.yuya_fungami),
            CardEntity(17, "Toyohiro Kanedaichi", Res.drawable.toyohiro),
            CardEntity(18, "Terunosuke Miyamoto", Res.drawable.miyamoto_terunosuke),
            CardEntity(19, "Tonio Trussardi", Res.drawable.tonio),
            CardEntity(20, "Aya Tsuji", Res.drawable.aya),


            CardEntity(1, "Crazy Diamond", Res.drawable.crazy_diamond),
            CardEntity(2, "Echoes", Res.drawable.echoes),
            CardEntity(3, "The Hand", Res.drawable.the_hand),
            CardEntity(4, "Heaven's Door", Res.drawable.heavens_door),
            CardEntity(5, "Killer Queen", Res.drawable.killer_queen),
            CardEntity(6, "Aqua Necklace", Res.drawable.aqua_necklace),
            CardEntity(7, "Bad Company", Res.drawable.bad_company),
            CardEntity(8, "The Lock", Res.drawable.the_lock),
            CardEntity(9, "Surface", Res.drawable.surface),
            CardEntity(10, "Love Deluxe", Res.drawable.love_deluxe),
            CardEntity(11, "Red Hot Chili Pepper", Res.drawable.red_hot_chili_peppers),
            CardEntity(12, "Ratt", Res.drawable.ratt),
            CardEntity(13, "Harvest", Res.drawable.harvest),
            CardEntity(14, "Atom Heart Father", Res.drawable.atom_heart_father),
            CardEntity(15, "Boy II Man", Res.drawable.boy_ii_man),
            CardEntity(16, "Highway Star", Res.drawable.highway_star),
            CardEntity(17, "Super Fly", Res.drawable.super_fly),
            CardEntity(18, "Enigma", Res.drawable.enigma),
            CardEntity(19, "Pearl Jam", Res.drawable.pearl_jam),
            CardEntity(20, "Cinderella", Res.drawable.cinderella),
            )
    }

    fun ObtainDeckPart5(): MutableList<CardEntity> {
        return mutableListOf(
            CardEntity(1, "Giorno Giovanna", Res.drawable.giorno_giovanna),
            CardEntity(2, "Bruno Bucciarati", Res.drawable.bruno_bucciarati),
            CardEntity(3, "Guido Mista", Res.drawable.guido_mista),
            CardEntity(4, "Naranccia Ghirga", Res.drawable.narancia_ghirga),
            CardEntity(5, "Diavolo", Res.drawable.diavolo),
            CardEntity(6, "Leone Abbacchio", Res.drawable.leone_abbacchio),
            CardEntity(7, "Pannacotta Fugo", Res.drawable.pannacotta_fugo),
            CardEntity(8, "Trish Una", Res.drawable.trish_una),
            CardEntity(9, "Polpo", Res.drawable.polpo),
            CardEntity(10, "Mario Zucchero", Res.drawable.mario_zucchero),
            CardEntity(11, "Sale", Res.drawable.sale),
            CardEntity(12, "Risotto Nero", Res.drawable.risotto_nero),
            CardEntity(13, "Formaggio", Res.drawable.formaggio),
            CardEntity(14, "Illuso", Res.drawable.illuso),
            CardEntity(15, "Prosciutto", Res.drawable.prosciutto),
            CardEntity(16, "Pesci", Res.drawable.pesci),
            CardEntity(17, "Melone", Res.drawable.melone),
            CardEntity(18, "Ghiaccio", Res.drawable.ghiaccio),
            CardEntity(19, "Cioccolata", Res.drawable.cioccolata),
            CardEntity(20, "Secco", Res.drawable.secco),

            CardEntity(1, "Gold Experience", Res.drawable.gold_experience),
            CardEntity(2, "Sticky Fingers", Res.drawable.sticky_fingers),
            CardEntity(3, "Sex Pistols", Res.drawable.sex_pistols),
            CardEntity(4, "Aerosmith", Res.drawable.aerosmith),
            CardEntity(5, "King Crimson", Res.drawable.king_crimson),
            CardEntity(6, "Moody Blues", Res.drawable.moody_blues),
            CardEntity(7, "Purple Haze", Res.drawable.purple_haze),
            CardEntity(8, "Spice Girl", Res.drawable.spice_girl),
            CardEntity(9, "Black Sabbath", Res.drawable.black_sabath),
            CardEntity(10, "Soft Machine", Res.drawable.soft_machine),
            CardEntity(11, "Kraft Work", Res.drawable.kraft_work),
            CardEntity(12, "Metallica", Res.drawable.metallicca),
            CardEntity(13, "Little Feet", Res.drawable.little_feet),
            CardEntity(14, "Man in the Mirror", Res.drawable.man_in_the_mirror),
            CardEntity(15, "Beach Boy", Res.drawable.beach_boy),
            CardEntity(16, "The Grateful Dead", Res.drawable.the_grateful_dead),
            CardEntity(17, "Baby Face", Res.drawable.baby_face),
            CardEntity(18, "White Album", Res.drawable.white_album),
            CardEntity(19, "Green Day", Res.drawable.green_day),
            CardEntity(20, "Oasis", Res.drawable.oasis),
            )
    }

    fun ObtainDeckPart6(): MutableList<CardEntity> {
        return mutableListOf(
            CardEntity(1, "Jolyne Kujo", Res.drawable.jolyne_kujo),
            CardEntity(2, "Ermes Costello", Res.drawable.ermes_costello),
            CardEntity(3, "Narciso Anasui", Res.drawable.narciso_anasui),
            CardEntity(4, "Enrico Pucci", Res.drawable.enrico_pucci),
            CardEntity(5, "Emporio Alnino", Res.drawable.emporio_alnino),
            CardEntity(6, "F.F", Res.drawable.ff),
            CardEntity(7, "Weather Report", Res.drawable.weather_report),
            CardEntity(8, "Gwess", Res.drawable.gwess),
            CardEntity(9, "Johngalli A.", Res.drawable.johngalli_a),
            CardEntity(10, "Thunder McQueen", Res.drawable.thunder_mcqueen),
            CardEntity(11, "Miraschon", Res.drawable.miraschon),
            CardEntity(12, "Lang Rangler", Res.drawable.lang_rangler),
            CardEntity(13, "Sports Maxx", Res.drawable.sports_maxx),
            CardEntity(14, "Viviano Westwood", Res.drawable.westwood),
            CardEntity(15, "Kenzou", Res.drawable.kenzou),
            CardEntity(16, "D and G", Res.drawable.d_g),
            CardEntity(17, "Miuccia Miuller", Res.drawable.miu_miu),
            CardEntity(18, "Ungalo", Res.drawable.ungalo),
            CardEntity(19, "Rikiel", Res.drawable.rikiel),
            CardEntity(20, "Donatello Versus", Res.drawable.donatello_versus),

            CardEntity(1, "Stone Free", Res.drawable.stone_free),
            CardEntity(2, "Kiss", Res.drawable.kiss),
            CardEntity(3, "Diver Down", Res.drawable.diver_down),
            CardEntity(4, "Whitesnake", Res.drawable.whitesnake),
            CardEntity(5, "Burning Down the House", Res.drawable.burning_down_the_house),
            CardEntity(6, "Foo Fighters", Res.drawable.foo_fighters),
            CardEntity(7, "Weather Report", Res.drawable.weather_report_stand),
            CardEntity(8, "Goo Goo Dolls", Res.drawable.goo_goo_dolls),
            CardEntity(9, "Manhattan Transfer", Res.drawable.manhattan_transfer),
            CardEntity(10, "Highway to Hell", Res.drawable.highway_to_hell),
            CardEntity(11, "Marilyn Manson", Res.drawable.marilyn_manson),
            CardEntity(12, "Jumpin' Jack Flash", Res.drawable.jumpin_jack_flash),
            CardEntity(13, "Limp Bizkit", Res.drawable.limp_bizkit),
            CardEntity(14, "Planet Waves", Res.drawable.planet_waves),
            CardEntity(15, "Dragon's Dream", Res.drawable.dragons_dream),
            CardEntity(16, "Yo-Yo Ma", Res.drawable.yo_yo_ma),
            CardEntity(17, "Jail House Lock", Res.drawable.jail_house_lock),
            CardEntity(18, "Bohemian Rhapsody", Res.drawable.bohemian_rhapsody),
            CardEntity(19, "Sky High", Res.drawable.sky_high),
            CardEntity(20, "Under World", Res.drawable.under_world),
            )
    }
}